### ISSUE TITLE
LOAD RECORDS | Ability to Save Field Mappings

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#303] opened 2023-04-14 01:54 UTC
This could be twofold. 

1. You do a repetitive upload, and you don't want to have to remap the fields each time
2. You are attempting to upload, and it keeps erroring out, so as you fix one thing and then the next, you must keep redoing the mappings. 

This could be a button within the action bar with a drop-down to Save as the main action and the sub-action to load the field mapping.

This could also be prompt when you click next to ask if they want to save the mappings. 🤷 

![Screenshot 2023-04-13 at 8 53 08 PM](https://user-images.githubusercontent.com/22582720/231921427-a91eace0-064c-4e98-8e11-61369ddd0e19.png)

**Comment by paustint** [comment] 2023-04-15 14:21
I will leave both open for now, but duplicate of #147

**Closed** 2023-04-28 00:10 UTC
Labels: enhancement
