### ISSUE TITLE
Value of filter criterion for field {boolean field} must be of type boolean and should not be enclosed in quotes

### ISSUE THREAD

**Issue by sscoles89** [jetstreamapp/jetstream#274] opened 2023-04-04 14:15 UTC
**Issue:** 
Boolean fields used in the query are failing without manual editing (removing the quotation marks) of the SOQL query. 

**Steps to reproduce:**
1. From the query records tab, select any object with a boolean field.
2. Select a boolean field in the filters.
3. Execute query.
4. Error shown with the following text: 
> There is an error with your query. Either [go back](https://getjetstream.app/app/query) to the query builder or manually adjust your query.
> 
> WHERE SBQQ__Product__r.Disable_Proration__c
>       ^
> ERROR at Row:3:Column:7
> value of filter criterion for field 'Disable_Proration__c' must be of type boolean and should not be enclosed in quotes

**Workaround:** 
Manually remove quotation marks and resubmit query.

**Expected behavior:** 
Query will automatically remove quotation marks from boolean fields in filters.

**Screenshots:**
![Screenshot 2023-04-04 at 9 00 36 AM](https://user-images.githubusercontent.com/129870421/229820389-e1c49399-4894-4567-869d-b3407bef3101.png)
![Screenshot 2023-04-04 at 9 01 00 AM](https://user-images.githubusercontent.com/129870421/229820402-f87df6a2-8bb9-41af-a311-34a15a185d6b.png)

**Browser and operating system:** 
MacBook Pro  - macOS Ventura - Version 13.2.1

**Comment by paustint** [comment] 2023-04-04 14:21
Duplicate of #270

@sscoles89 - This is resolved, but you may have been using a cached version of Jetstream so may have experienced the issue.

**Comment by sscoles89** [comment] 2023-04-04 14:21
Confirming that refresh resolved the issue.

**Closed as completed by paustint** 2023-04-04 14:21 UTC
Labels: bug
